import { validateScene } from "./scene.js";

function assTime(milliseconds) {
  const centiseconds = Math.max(0, Math.round(milliseconds / 10));
  const hours = Math.floor(centiseconds / 360000);
  const minutes = Math.floor((centiseconds % 360000) / 6000);
  const seconds = Math.floor((centiseconds % 6000) / 100);
  const fraction = centiseconds % 100;
  return `${hours}:${String(minutes).padStart(2, "0")}:${String(seconds).padStart(2, "0")}.${String(fraction).padStart(2, "0")}`;
}

function assColor(hex, alpha = "00") {
  const match = /^#([a-f0-9]{2})([a-f0-9]{2})([a-f0-9]{2})$/i.exec(hex);
  if (!match) throw new TypeError("ASS color is invalid");
  return `&H${alpha}${match[3]}${match[2]}${match[1]}&`.toUpperCase();
}

function escapeAss(value) {
  return String(value)
    .replace(/\\/g, "\\\\")
    .replace(/{/g, "\\{")
    .replace(/}/g, "\\}")
    .replace(/[\r\n]+/g, " ");
}

function deterministicParticles(scene) {
  let seed = Number.parseInt(scene.manifestSha256.slice(0, 8), 16) >>> 0;
  const random = () => {
    seed ^= seed << 13;
    seed ^= seed >>> 17;
    seed ^= seed << 5;
    return (seed >>> 0) / 0xffffffff;
  };
  const glyphs = [".", ":", "+", "·", "'", "*"];
  const particles = [];
  for (let index = 0; index < 28; index += 1) {
    const x1 = Math.round(random() * scene.layout.width);
    const y1 = Math.round(random() * scene.layout.height);
    const x2 = Math.max(0, Math.min(scene.layout.width, x1 + Math.round((random() - 0.5) * 90)));
    const y2 = Math.max(0, Math.min(scene.layout.height, y1 + Math.round((random() - 0.5) * 70)));
    particles.push({ x1, y1, x2, y2, glyph: glyphs[Math.floor(random() * glyphs.length)] });
  }
  return particles;
}

function cueText(cue) {
  const breaks = new Set(cue.lineBreakBeforeWordIndexes);
  const cueStart = cue.startsAtMs;
  return cue.words.map((word, index) => {
    const linePrefix = breaks.has(index) ? "\\N" : index === 0 ? "" : " ";
    const relativeStart = Math.max(0, Math.round((word.startsAtMs - cueStart) / 10));
    const duration = Math.max(1, Math.round((word.endsAtMs - word.startsAtMs) / 10));
    return `${linePrefix}{\\kt${relativeStart}\\k${duration}}${escapeAss(word.text)}`;
  }).join("");
}

export function compileAss(sceneValue, { fontName = "Inter" } = {}) {
  const scene = validateScene(sceneValue);
  const styles = scene.speakers.map((speaker) => {
    const name = speaker.id.replace("speaker-", "Speaker");
    return `Style: ${name},${fontName},${scene.layout.fontSize},${assColor(speaker.bright)},${assColor(speaker.dim)},&H00000000,&H90000000,0,0,0,0,100,100,0,0,1,2.2,0,7,0,0,0,1`;
  });
  const lines = [
    "[Script Info]",
    "; Generated by podcast-visualizer. Do not edit.",
    "ScriptType: v4.00+",
    "WrapStyle: 2",
    "ScaledBorderAndShadow: yes",
    `PlayResX: ${scene.layout.width}`,
    `PlayResY: ${scene.layout.height}`,
    "YCbCr Matrix: TV.709",
    "",
    "[V4+ Styles]",
    "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding",
    `Style: Title,${fontName},${Math.round(scene.layout.fontSize * 0.62)},&H00E9E5E1,&H00E9E5E1,&H00000000,&H00000000,0,0,0,0,100,100,3,0,1,0,0,7,0,0,0,1`,
    `Style: Dust,IBM Plex Mono,${Math.round(scene.layout.fontSize * 0.36)},&H00B8AAA0,&H00B8AAA0,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,0,0,7,0,0,0,1`,
    ...styles,
    "",
    "[Events]",
    "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
    `Dialogue: 2,${assTime(scene.title.startsAtMs)},${assTime(scene.title.endsAtMs)},Title,,0,0,0,,{\\an7\\pos(${scene.layout.marginX},${scene.layout.cardY})\\fad(240,280)\\bord0}:: DUST WAVE / AUDIO TRANSCRIPT`,
    `Dialogue: 2,${assTime(scene.title.startsAtMs + 260)},${assTime(scene.title.endsAtMs)},Title,,0,0,0,,{\\an7\\pos(${scene.layout.marginX},${scene.layout.cardY + scene.layout.fontSize})\\fad(240,280)\\fs${Math.round(scene.layout.fontSize * 0.9)}}${escapeAss(scene.title.text)}`
  ];
  if (scene.styleVersion === "dust-subtle-v1") {
    for (const particle of deterministicParticles(scene)) {
      lines.push(`Dialogue: 0,${assTime(0)},${assTime(scene.durationMs)},Dust,,0,0,0,,{\\an5\\alpha&HDC&\\move(${particle.x1},${particle.y1},${particle.x2},${particle.y2},0,${scene.durationMs})\\fad(800,800)}${particle.glyph}`);
    }
  }
  for (const cue of scene.cues) {
    const style = cue.speakerId.replace("speaker-", "Speaker");
    lines.push(`Dialogue: 3,${assTime(cue.startsAtMs)},${assTime(cue.endsAtMs)},${style},,0,0,0,,{\\an${cue.position.anchor}\\pos(${cue.position.x},${cue.position.y})\\fad(90,120)\\q2}${cueText(cue)}`);
  }
  return `${lines.join("\n")}\n`;
}
